//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinetix.Reporting {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SRDocType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SRDocType() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kinetix.Reporting.SRDocType", typeof(SRDocType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        /// &lt;!ELEMENT {0} ({1},{2},{3},{8},{9})&gt;
        /// &lt;!ELEMENT {1} ({5})+&gt;
        /// &lt;!ELEMENT {2} ({5})+&gt;
        /// &lt;!ELEMENT {3} ({4})+&gt;
        /// &lt;!ELEMENT {4} ({5})+&gt;
        /// &lt;!ELEMENT {5} (#PCDATA)&gt;
        /// &lt;!ELEMENT {8} (#PCDATA)&gt;
        /// &lt;!ELEMENT {9} (#PCDATA)&gt;
        /// &lt;!ATTLIST {5} {6} CDATA #REQUIRED&gt;
        /// &lt;!ATTLIST {5} {7} CDATA #IMPLIED&gt;
        /// &lt;!ATTLIST {5} {10} CDATA #IMPLIED&gt;
        ///	 .
        /// </summary>
        public static string ReportToExcelDocType {
            get {
                return ResourceManager.GetString("ReportToExcelDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        /// &lt;!ELEMENT {0} ({1})&gt;
        /// &lt;!ELEMENT {1} ({2}|{3})*&gt;
        /// &lt;!ELEMENT {2} ({3}*|{4}+)&gt;
        /// &lt;!ELEMENT {3} ({2}*|{4}+)&gt;
        /// &lt;!ELEMENT {4} (#PCDATA)&gt;
        /// &lt;!ATTLIST {2} {5} CDATA #REQUIRED&gt;
        /// &lt;!ATTLIST {3} {5} CDATA #REQUIRED&gt;
        /// &lt;!ATTLIST {4} {5} CDATA #REQUIRED&gt;
        ///	 .
        /// </summary>
        public static string ReportToPdfDocType {
            get {
                return ResourceManager.GetString("ReportToPdfDocType", resourceCulture);
            }
        }
    }
}
