Declare @WFA_ID_WFW_ID_LIST as table(WFA_ID int, WFW_ID int);	

INSERT INTO WF_ACTIVITY (
	CREATION_DATE,
	WFW_ID,
	WFAD_ID,
	IS_AUTO,
	IS_VALID
)
Output
	inserted.WFA_ID, inserted.WFAD_ID
into
	@WFA_ID_WFAD_ID_LIST
Select CREATION_DATE, WFW_ID, WFAD_ID, IS_AUTO, IS_VALID
  FROM @table tab;


INSERT INTO WF_DECISION(
	USERNAME,
	CHOICE,
	DECISION_DATE,
	COMMENTS
)
SELECT USERNAME, CHOICE, DECISION_DATE, COMMENTS
FROM @table tab
JOIN @WFA_ID_WFAD_ID_LIST wfa_wfad ON (tab.WFAD_ID = wfa_wfad.WFAD_ID);

