
DELETE WDE 
  FROM WF_ACTIVITY WFA
  JOIN WF_DECISION WDE ON (WFA.WFA_ID = WDE.WFA_ID)
 WHERE WFA.WFW_ID = @WFW_ID;

DELETE 
  FROM WF_ACTIVITY 
 WHERE WFW_ID = @WFW_ID;

 DELETE 
   FROM WF_WORKFLOW
  WHERE WFW_ID = @WFW_ID;
  