SELECT 
	WAD.WFAD_ID AS WfadId,
	WAD.NAME AS Name,
	WAD.LEVEL AS Level,
	WAD.WFMD_CODE AS WfmdCode,
	WAD.WFWD_ID AS WfwdId
FROM 
	WF_WORKFLOW_DEFINITION WFD
	JOIN WF_ACTIVITY_DEFINITION WAD ON (WFD.WFWD_ID = WAD.WFWD_ID)
WHERE WAD.WFWD_ID = @WFWD_ID
  AND WAD.LEVEL >= @LEVEL
  AND (WAD.WFAD_ID = WFD.WFAD_ID
	   OR WAD.WFAD_ID IN (SELECT WTR.WFAD_ID_TO
							FROM WF_TRANSITION_DEFINITION WTR 
							WHERE (WTR.WFWD_ID = WFD.WFWD_ID AND WTR.NAME = @NAME)))
ORDER BY WAD.LEVEL;

