SELECT 
	ACT.*
FROM 
	WF_ACTIVITY ACT
	JOIN WF_ACTIVITY_DEFINITION ACD ON (ACT.WFAD_ID = ACD.WFAD_ID)
WHERE 
	ACD.WFAD_ID IN (SELECT VAL FROM @ACT_DEF_ID)
	AND ACT.WFW_ID = @WFW_ID
ORDER BY
	ACD.LEVEL
;
