SELECT 
	WAD.WFAD_ID AS WfadId,
	WAD.NAME AS Name,
	WAD.LEVEL AS Level,
	WAD.WFMD_CODE AS WfmdCode,
	WAD.WFWD_ID AS WfwdId
FROM 
	WF_ACTIVITY_DEFINITION WAD
	JOIN WF_TRANSITION_DEFINITION WTR ON (WTR.WFAD_ID_FROM = WAD.WFAD_ID AND WTR.NAME = @NAME)
WHERE WAD.WFWD_ID = @WFWD_ID
ORDER BY WAD.LEVEL;
