SELECT 
	RFD.*
FROM 
	RULE_FILTER_DEFINITION RFD
	JOIN SELECTOR_DEFINITION SEL ON (RFD.SEL_ID = SEL.ID)
	JOIN WF_ACTIVITY_DEFINITION WAD ON (SEL.ITEM_ID = WAD.WFAD_ID)
WHERE 
	WAD.WFWD_ID = @WFWD_ID;
