// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Kinetix.SpaServiceGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Kinetix.SpaServiceGenerator.Model;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ServiceSpa : ServiceSpaBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("/*\r\n    Ce fichier a été généré automatiquement.\r\n    Toute modification sera per" +
                    "due.\r\n*/\r\n\r\n/* tslint:disable */\r\nimport * as server from \"../server\";\r\n");
            
            #line 14 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
 foreach (var import in GetImportList()) { 
            
            #line default
            #line hidden
            this.Write("import {");
            
            #line 15 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import.Item1));
            
            #line default
            #line hidden
            this.Write("} from \"");
            
            #line 15 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import.Item2));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 15 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import.Item3));
            
            #line default
            #line hidden
            this.Write("\";\r\n");
            
            #line 16 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
 } 
            
            #line default
            #line hidden
            
            #line 17 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
 foreach (var service in Services) { 
            
            #line default
            #line hidden
            this.Write("\r\n/**\r\n * ");
            
            #line 20 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Documentation.Summary));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 21 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
 foreach (var param in service.Documentation.Parameters) { 
            
            #line default
            #line hidden
            this.Write(" * @param ");
            
            #line 21 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(param.Item1));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 21 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(param.Item2));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 22 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
 } 
            
            #line default
            #line hidden
            this.Write(" * @param options Options to service call.\r\n */\r\nexport function ");
            
            #line 25 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.ToFirstLower(service.Name)));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 25 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
 
    if (service.BodyParameters.Any()) {
        var parameter = service.BodyParameters.First();
        
            
            #line default
            #line hidden
            
            #line 28 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            
            #line 28 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.IsOptional ? "?" : ""));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 28 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTSType(parameter.Type)));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 28 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"

    }
    foreach (var parameter in service.UriParameters) { 
            
            #line default
            #line hidden
            
            #line 30 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            
            #line 30 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.IsOptional ? "?" : ""));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 30 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTSType(parameter.Type)));
            
            #line default
            #line hidden
            
            #line 30 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"

        if (parameter.Name != service.UriParameters.Last().Name) {
            
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 32 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"

        }
    }
    if (service.UriParameters.Count() > 0) { 
        
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 36 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"

    } 
            
            #line default
            #line hidden
            this.Write("options: server.RequestInitExtended<{");
            
            #line 37 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
 
        foreach (var queryParameter in service.QueryParameters) { 
            
            
            #line default
            #line hidden
            
            #line 39 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryParameter.Name));
            
            #line default
            #line hidden
            
            #line 39 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryParameter.IsOptional ? "?" : ""));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 39 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTSType(queryParameter.Type)));
            
            #line default
            #line hidden
            
            #line 39 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"

            if (queryParameter.Name != service.QueryParameters.Last().Name) {
                
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 41 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"

            }	
        }
    
            
            #line default
            #line hidden
            this.Write("}> = {}) {\r\n    return server.");
            
            #line 45 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.ToFirstLower(service.Verb)));
            
            #line default
            #line hidden
            this.Write("<");
            
            #line 45 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTSType(service.ReturnType)));
            
            #line default
            #line hidden
            this.Write(", {");
            
            #line 45 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
 
            foreach (var queryParameter in service.QueryParameters) { 
                
            
            #line default
            #line hidden
            
            #line 47 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryParameter.Name));
            
            #line default
            #line hidden
            
            #line 47 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryParameter.IsOptional ? "?" : ""));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 47 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTSType(queryParameter.Type)));
            
            #line default
            #line hidden
            
            #line 47 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"

                if (queryParameter.Name != service.QueryParameters.Last().Name) {
                    
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 49 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"

                }	
            }
        
            
            #line default
            #line hidden
            this.Write("}>(`./");
            
            #line 52 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.Route.Replace("{", "${").Replace("?", "")));
            
            #line default
            #line hidden
            this.Write("`");
            
            #line 52 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"

        if (service.BodyParameters.Any()) {
            
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 54 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(service.BodyParameters.First().Name));
            
            #line default
            #line hidden
            
            #line 54 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"

        }
        
            
            #line default
            #line hidden
            
            #line 56 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
 
        if (!service.BodyParameters.Any() && service.IsPostPutMethod) {
            
            
            #line default
            #line hidden
            this.Write(", {} ");
            
            #line 58 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"

        }
        
            
            #line default
            #line hidden
            this.Write(", options);\r\n}\r\n");
            
            #line 62 "D:\Projects\kinetix\Kinetix-tools\Kinetix.SpaServiceGenerator\ServiceSpa.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class ServiceSpaBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
