
DELETE RCD 
  FROM RULE_CONDITION_DEFINITION RCD 
  JOIN RULE_DEFINITION RUD ON (RUD.ID = RCD.RUD_ID)
 WHERE RUD.ID IN (SELECT VAL FROM @ITEMS_ID);

DELETE 
  FROM RULE_DEFINITION 
 WHERE ID IN (SELECT VAL FROM @ITEMS_ID);
