
DELETE RUF 
  FROM RULE_FILTER_DEFINITION RUF
  JOIN SELECTOR_DEFINITION SEL ON (SEL.ID = RUF.SEL_ID)
 WHERE SEL.ID IN (SELECT VAL FROM @ITEMS_ID);

DELETE 
  FROM SELECTOR_DEFINITION 
 WHERE ID IN (SELECT VAL FROM @ITEMS_ID);
