SELECT 
	RUD.ITEM_ID AS ItemId
FROM 
	RULE_DEFINITION RUD
	JOIN RULE_CONDITION_DEFINITION RCD ON (RCD.RUD.ID = RUD.ID)
WHERE 
	RCD.FIELD = @FIELD_1
AND RCD.VALUE = @VALUE_1
[if notnull="field2"]
AND EXIST (SELECT 1 FROM RULE_CONDITION_DEFINITION RCD2 RCD2.FIELD = @FIELD_2 AND RCD.VALUE = @VALUE_2 AND RCD2.RUD.ID = RUD.ID)
[/if]
;
