
CREATE TYPE WF_ACTIVITY_UPDATE_TABLE_TYPE as TABLE
(
	WFA_ID INT,
	IS_AUTO bit not null,
	IS_VALID bit not null,
	INSERT_KEY INT
)
GO

GRANT EXECUTE ON TYPE::[dbo].[WF_ACTIVITY_UPDATE_TABLE_TYPE] TO PUBLIC;
go