//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinetix.ServiceModel {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kinetix.ServiceModel.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ReferenceAccessor must return ICollection&lt;&gt;.
        /// </summary>
        public static string ExceptionAccessorMustReturnCollection {
            get {
                return ResourceManager.GetString("ExceptionAccessorMustReturnCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ReferenceAccessor with parameters.
        /// </summary>
        public static string ExceptionAccessorWithParameters {
            get {
                return ResourceManager.GetString("ExceptionAccessorWithParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ReferenceAccessor with too many generic types.
        /// </summary>
        public static string ExceptionAccessorWithTooManyGenericArgs {
            get {
                return ResourceManager.GetString("ExceptionAccessorWithTooManyGenericArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à contract n&apos;est pas une interface.
        /// </summary>
        public static string ExceptionContractNotAnInterface {
            get {
                return ResourceManager.GetString("ExceptionContractNotAnInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas de constructeur pour le service {0}.
        /// </summary>
        public static string ExceptionMissingConstructor {
            get {
                return ResourceManager.GetString("ExceptionMissingConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible d&apos;instancier le service {0} : {1}.
        /// </summary>
        public static string ExceptionServiceInstanciation {
            get {
                return ResourceManager.GetString("ExceptionServiceInstanciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type : {0}.
        /// </summary>
        public static string ExceptionTypeDescription {
            get {
                return ResourceManager.GetString("ExceptionTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type {0} has a ReferenceAccessor in {1}/{2} but is not marked as Reference type..
        /// </summary>
        public static string WarningReferenceListNotMarkedAsReference {
            get {
                return ResourceManager.GetString("WarningReferenceListNotMarkedAsReference", resourceCulture);
            }
        }
    }
}
