//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinetix.Data.SqlClient.Test {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlResource {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlResource() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kinetix.Data.SqlClient.Test.SqlResource", typeof(SqlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to select * from dual where 1=1 
        ///    [if null=&quot;PAR1&quot;]and PAR1 IS NULL[/if]
        ///    [if notnull=&quot;PAR1&quot;]and PAR1 IS NOT NULL[/if]
        ///    [if equals=&quot;PAR1:2&quot;]and PAR1 = 2[/if]
        ///    [if notequals=&quot;PAR1:2&quot;]and PAR1 != 2[/if]
        ///    [if notnull=&quot;PAR1&amp;PAR2&quot;]and PAR1 = PAR2[/if]
        ///    [if null=&quot;PAR1|PAR2&quot;]and VALUE = 1[/if]
        ///  .
        /// </summary>
        internal static string SqlTest {
            get {
                return ResourceManager.GetString("SqlTest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to select * from dual where 1=1 
        ///    [if null=&quot;PAR1|PAR2&amp;PAR3&quot;]and VALUE = 1[/if]
        ///  .
        /// </summary>
        internal static string SqlTestAndOr {
            get {
                return ResourceManager.GetString("SqlTestAndOr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to select * from dual where {Bean.CINQ} = 5
        ///.
        /// </summary>
        internal static string SqlTestConst {
            get {
                return ResourceManager.GetString("SqlTestConst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to select * from dual [if equals=&quot;PAR1:{Bean.CINQ}&quot;]where 1 = 1[/if].
        /// </summary>
        internal static string SqlTestConstIf {
            get {
                return ResourceManager.GetString("SqlTestConstIf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SqlTestEmpty {
            get {
                return ResourceManager.GetString("SqlTestEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to select * from dual where 1=1 
        ///    [if badClause=&quot;PAR1|PAR2&amp;PAR3&quot;]and VALUE = 1[/if]
        ///  .
        /// </summary>
        internal static string SqlTestIfBadClause {
            get {
                return ResourceManager.GetString("SqlTestIfBadClause", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to select * from dual where 1=1 
        ///    [if notnull=&quot;PAR1|PAR2&quot;]
        ///      [if notnull=&quot;PAR1&quot;]and PAR1 IS NOT NULL[/if]
        ///      [if notnull=&quot;PAR2&quot;]and PAR2 IS NOT NULL[/if]
        ///      and VALUE = 1
        ///    [/if]
        ///  .
        /// </summary>
        internal static string SqlTestIfCascade {
            get {
                return ResourceManager.GetString("SqlTestIfCascade", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to select * from dual where 1=1 
        ///    [if badClause=&quot;PAR1|PAR2&amp;PAR3&quot;
        ///  .
        /// </summary>
        internal static string SqlTestIfMalformed {
            get {
                return ResourceManager.GetString("SqlTestIfMalformed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to select * from dual where 1=1 
        ///  .
        /// </summary>
        internal static string SqlTestSimple {
            get {
                return ResourceManager.GetString("SqlTestSimple", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to select * from dual where {CurrentUserId} IS NOT NULL.
        /// </summary>
        internal static string SqlTestUserId {
            get {
                return ResourceManager.GetString("SqlTestUserId", resourceCulture);
            }
        }
    }
}
